### ISSUE TITLE
Unknown SMPP command code "0x428"

### ISSUE THREAD

**Issue by sajuptpm** [python-smpplib/python-smpplib#2]
I could send SMS using the example code given in the github

But, Getting following errors at the end.
```
('====pdu.sequence======', 1)
DEBUG:smpplib.client:Waiting for PDU...
DEBUG:smpplib.client:<<0000003a80000004000000000000000133346630616331622d613131642d343137622d383730622d666562303435636664633333000428000100 (58 bytes)
Traceback (most recent call last):
  File "test2.py", line 41, in <module>
    client.listen()
  File "build/bdist.linux-x86_64/egg/smpplib/client.py", line 247, in listen
  File "build/bdist.linux-x86_64/egg/smpplib/client.py", line 190, in read_pdu
  File "build/bdist.linux-x86_64/egg/smpplib/smpp.py", line 46, in parse_pdu
  File "build/bdist.linux-x86_64/egg/smpplib/pdu.py", line 134, in parse
  File "build/bdist.linux-x86_64/egg/smpplib/command.py", line 328, in parse_params
  File "build/bdist.linux-x86_64/egg/smpplib/command.py", line 355, in parse_optional_params
  File "build/bdist.linux-x86_64/egg/smpplib/command.py", line 73, in get_optional_name
smpplib.exceptions.UnknownCommandError: Unknown SMPP command code "0x428"
DEBUG:smpplib.client:Sending unbind PDU
DEBUG:smpplib.client:>>00000010000000060000000000000001 (16 bytes)
DEBUG:smpplib.client:Waiting for PDU...
DEBUG:smpplib.client:<<00000010800000060000000000000001 (16 bytes)
DEBUG:smpplib.client:Read unbind_resp PDU
INFO:smpplib.client:Disconnecting...
```

**Comment by baverman** [comment]
This bug is related to invalid parsing in parse_optional_params.

**Comment by dotpmrcunha** [comment]
Any news from this related to this bug? I also have this problem when receiving Delivery Report with code 1501.

"Session operation
The 0x1501 TLV field is used in certain scenarios to perform specific operations on end-user
subscriptions that are managed by the mobile operators. It can be present in both DELIVER_SM and
SUBMIT_SM messages. Please refer to the particular workflow documents for more detailed
information. "

**Comment by baverman** [comment]
@dotpmrcunha i've fixed the bug in https://github.com/podshumok/python-smpplib/pull/18

**Comment by podshumok** [comment]
Can anybody confirm that the bug is fixed?

**Comment by dotpmrcunha** [comment]
Still getting: UnknownCommandError: Unknown SMPP command code "0x1501"

TRACE
==========================================
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/client.py", line 275, in listen
    p = self.read_pdu()
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/client.py", line 218, in read_pdu
    p = smpp.parse_pdu(raw_pdu, client=self)
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/smpp.py", line 46, in parse_pdu
    new_pdu.parse(data)
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/pdu.py", line 133, in parse
    self.parse_params(data[16:])
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/command.py", line 332, in parse_params
    self.parse_optional_params(data[pos:])
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/command.py", line 347, in parse_optional_params
    field = get_optional_name(type_code)
  File "/home/Envs/dev1/lib/python2.7/site-packages/smpplib/command.py", line 73, in get_optional_name
    'Unknown SMPP command code "0x%x"' % code)
UnknownCommandError: Unknown SMPP command code "0x1501"
=====================================================================

You could provide a way to add specific vendor attributes, you think is possible?

Regards.

**Comment by novns** [comment]
I'm getting similar UnknownCommandError: Unknown SMPP command code "0x1403".
Please fix it or allow adding custom attributes.
Thank you!

**Comment by eigenein** [comment]
Closing this in favor of #105
